http:
 hostname: 'localhost'
 port: '8081'
 
 
dbconnection:
  hostname: 'db4free.net'
  port: '3306'
  username: 'c4ebatch5'
  password: 'c4ebatch@5'
  dbname: 'testdbc45'
  
httprequest:
  hostname: 'walmart.p.rapidapi.com'
  path: '/stores/list'
    